### ISSUE TITLE
Move the device settings save button to the header

### ISSUE THREAD

**Issue by Ingvord** [waltz-controls/waltz-grid-widget#9]
Once user clicks on the *settings* button in the header (see #7 ) a new *save* button must appear next to it.

**Motivation:** in the settings view it is cumbersome to scroll down every time the settings must be changed. Moreover in case of long list of attributes and commands it is not clear immediately to scroll down to reach the *save* button 

Related to #7

**Comment by kapot65** [comment]
Issue is outdated due to new interface
Data view:
![widget_view](https://user-images.githubusercontent.com/20247839/105984927-ddb17200-60ab-11eb-89f0-c25ddb96be54.png)
Config view:
![widget_config](https://user-images.githubusercontent.com/20247839/105984925-db4f1800-60ab-11eb-87ab-a57ef862294a.png)
